name: Pack into executable
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      WEIGHTS_URL: https://github.com/zeithrold/dut-fire-detect/releases/download/v1.0.0/fire.pt
    steps:
      - uses: actions/checkout@v2
      - name: Make weights directory
        run: |
          mkdir weights
      - name: Download weights (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri $env:WEIGHTS_URL -OutFile weights/fire.pt
      - name: Download weights (Linux and macOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          curl -L $WEIGHTS_URL -o weights/fire.pt
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies (with CUDA)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dependencies (without CUDA)
        if: matrix.os == 'macos-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.darwin.txt
      - name: Build executable
        run: |
          python -m PyInstaller app.spec
      - name: Move weights
        run: |
          mv weights dist/app
      - name: Make archive
        run: |
          7z a -tzip dist/app.zip dist/app
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: dist/app.zip
