name: Pack into executable
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        backend: [cuda, directml, cpu]
        exclude:
          - os: macos-latest
            backend: directml
          - os: macos-latest
            backend: cuda
          - os: macos-13
            backend: cuda
          - os: macos-13
            backend: directml
          - os: ubuntu-latest
            backend: directml
    runs-on: ${{ matrix.os }}
    env:
      WEIGHTS_URL: https://github.com/zeithrold/dut-fire-detect/releases/download/v1.1.0/model.onnx
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Make weights directory
        run: |
          mkdir weights
      - name: Download weights
        run: |
          aria2c -x 16 -s 16 -d weights ${{ env.WEIGHTS_URL }}
      - name: Install pip-tools
        run: |
          pip install pip-tools
      - name: Generate requirements
        run: |
          pip-compile --output-file requirements.txt --extra ${{ matrix.backend }} pyproject.toml
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build executable
        run: |
          python -m PyInstaller dire-detect.spec
      - name: Move weights
        run: |
          mv weights dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ runner.os }}-${{ runner.arch }}-${{ matrix.backend }}
          path: dist
